server:
  port: 8955

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  ai:
    vectorstore:
      pgvector:
        dimensions: 768
        index-type: hnsw
        distance-type: cosine_distance
#       TODO: That one does not work - see the bug: https://github.com/spring-projects/spring-ai/issues/4845
        initialize-schema: true
    ollama:
      embedding:
        options:
          model: nomic-embed-text:v1.5
      base-url: http://localhost:11434
      chat:
        options:
          keep_alive: 5m
          format: json
          model: deepseek-r1:latest
    model:
      embedding: ollama
